### ISSUE TITLE
Integrating WtP pipeline to a snakemake pipeline and adding workflow controls

### ISSUE THREAD

**Issue by lingyi-owl** [replikation/What_the_Phage#154]
Dear WtP developers,

I am making a snakemake pipeline having WtP integrated. The rule of WtP is attached below:
```
rule wtp:
    input:
        expand("results/wtp/input/{sample}_scaffolds_gt{length}.fasta",
                sample=ALL_SAMPLES, length=LENGTH)
    output:
        expand("results/wtp/output/{sample}_scaffolds_gt{length}/raw_data/virnet_results_{sample}_scaffolds_gt{length}.tar.gz",
                sample=ALL_SAMPLES, length=LENGTH),
    log:
        ".nextflow.log"
    conda:
        "../envs/wtp.yaml"
    params:
        fasta="'results/wtp/input/*.fasta'",
        pipeline="replikation/What_the_Phage",
        revision="v1.0.2",
        profile=["local", "singularity"],
        workdir=config["WTP"]["workdir"],
        databases=config["WTP"]["databases"],
        cachedir=config["WTP"]["cachedir"],
        output=config["WTP"]["outputdir"],
        cores=config["WTP"]["threads"],
        identify='',

    handover: True
    wrapper:
        "0.74.0/utils/nextflow"

```

For the user convenience, it is better not to change the code in the rules. We use a config.yaml file for adjusting the parameters instead.
I set the workdir path, database path and other parameters in the config file. Now I also want to add the workflow control options to the config file so the line 
` identify='',` in rule wtp will become:
`identify=config["WTP"]["identify"],`

The users can adjust the parameter of 'identify' in the config file.
The config file is attached below:

```
############
# WTP #
############
WTP:
    workdir: results/wtp/workdir
    databases: /net/phage/linuxhome/mgx/people/lingyi/wtp_databases
    cachedir: /home/nikos/nikos2/wtp_test/singularity_images
    outputdir: results/wtp/output
    threads: 46
    identify:
```

My questions is what I should put in the `identify:` option in the config file to activate and deactivate the option of "only phage identification, skips analysis".

I am looking forward to your input.

Best,
Lingyi
